name: Bugs or configuration issues
description: For any potential bugs or issues with configuring the plugin
title: "[Bug]: "
labels: ["bug"]
assignees: olimorris

body:
    - type: markdown
      attributes:
        value: |
          Thanks for taking the time to fill out this bug report! This form may seem onerous but it makes a resolution much quicker for you and I.
    - type: markdown
      attributes:
        value: |
          ## Test with a `minimal.lua` file
          I know the temptation is to skip this step but please don't. So many issues with the colorscheme are caused by other plugins overwriting highlight groups. This step helps to determine if the issue is actually with the plugin.

          Firstly, test and run Neovim with the minimal config below. Be sure to add your OneDarkPro config, saving to a `minimal.lua` file and adding any additional plugins you may need:
          ```lua
          -- ignore default config and plugins
          vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
          vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

          -- append test directory
          local test_dir = "/tmp/onedarkpro"
          vim.opt.runtimepath:append(vim.fn.expand(test_dir))
          vim.opt.packpath:append(vim.fn.expand(test_dir))

          -- install packer
          local install_path = test_dir .. "/pack/packer/start/packer.nvim"
          local install_plugins = false

          if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
              vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
              vim.cmd("packadd packer.nvim")
              install_plugins = true
          end

          local packer = require("packer")

          packer.init({
              package_root = test_dir .. "/pack",
              compile_path = test_dir .. "/plugin/packer_compiled.lua",
          })

          -- install plugins
          packer.startup(function(use)
              use("wbthomason/packer.nvim")
              use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
              use("olimorris/onedarkpro.nvim")

              -- Add any additional plugins here

              if install_plugins then
                  packer.sync()
              end
          end)

          -- setup treesitter
          local ok, treesitter = pcall(require, "nvim-treesitter.configs")
          if ok then
              treesitter.setup({
                  ensure_installed = "all",
                  ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
                  highlight = { enable = true },
              })
          end

          -- setup onedarkpro
          local ok, onedarkpro = pcall(require, "onedarkpro")
          if ok then
              onedarkpro.setup({
                -- Your onedarkpro config here
              })
              vim.cmd("colorscheme onedark")
          end
          ```

          Once you've updated for your config, run Neovim with this command:
          ```sh
          nvim --clean -u minimal.lua
          ```
          > **Note:** You may need to do this a couple of times for Treesitter to fully download and sync

    - type: textarea
      id: onedarkpro-config
      attributes:
        label: Your OneDarkPro config
        description: Please paste your specific OneDarkPro config
        placeholder: |
          ```lua
          -- Your onedarkpro config here
          ```
      validations:
        required: true

    - type: textarea
      id: errors
      attributes:
        label: Error messages
        description: Please paste any error messages you receive
        placeholder: |
          ```lua
          -- Error messages here
          ```
      validations:
        required: false

    - type: textarea
      id: bug
      attributes:
        label: Describe the bug
        description: Please describe the bug and include any screenshots
        placeholder: |
          ### What I expect to happen
          [Your text here]

          ### What actually happens
          [Your text here]
      validations:
        required: true

    - type: textarea
      id: reproduce
      attributes:
        label: Reproduce the bug
        description: Please include the steps to reproduce the bug
        placeholder: |
          Steps to reproduce:
          1.
          2.
          3.
      validations:
        required: false

    - type: checkboxes
      id: final-checks
      attributes:
        label: Final checks
        description: |
          Before you submit, please make sure you have completed the following steps:
        options:
          - label: I have made sure this issue exists in the latest version of the plugin
            required: true
          - label: I have tested with the `minimal.lua` config file above and still get the issue
            required: true
          - label: I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
            required: true
          - label: I have made sure this is not a duplicate issue
            required: true
