name: General (non bug) issue
description: For general issues, questions or feature requests
assignees: olimorris

body:
    - type: textarea
      id: description
      attributes:
        label: Issue/Question/Feature request
        description: Please include the detail of your issue below
        placeholder: Your issue
      validations:
        required: true

