name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  # Taken from the amazing work of:
  # https://github.com/EdenEast/nightfox.nvim/blob/main/.github/workflows/ci.yml
  fingerprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate fingerprint
        run: make fingerprint

      - name: Check if fingerprint changed
        id: check_fingerprint
        run: |
          [[ -n $(git diff-index HEAD --) ]] && status="commit" || status="skip"
          echo "status=$status" >> $GITHUB_OUTPUT

      - if: steps.check_fingerprint.outputs.status == 'commit'
        name: Commit fingerprint
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update fingerprint"
          commit_author: olimorris <olimorris@users.noreply.github.com >

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
          - os: ubuntu-latest
            url: https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.tar.gz

    steps:
      - uses: actions/checkout@v2

      - run: date +%F > todays-date
      - name: Restore from todays cache
        uses: actions/cache@v2
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.url }}-${{ hashFiles('todays-date') }}

      - name: Prepare
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL ${{ matrix.url }} | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test
